### ISSUE TITLE
Compilation error on file lib/country.ex

### ISSUE THREAD

**Issue by andruby** [SebastianSzturo/countries#4]
Stacktrace:

```
== Compilation error on file lib/country.ex ==
** (ArgumentError) Access is not a protocol, cannot derive Access for Countries.Country
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    (elixir) lib/protocol.ex:591: Protocol.derive/5
    (stdlib) lists.erl:1337: :lists.foreach/2
    (elixir) lib/protocol.ex:579: Protocol.__derive__/3
    lib/country.ex:3: (module)
```

On Elixir 1.1.1

**Comment by andruby** [comment]
This is probably due to deprecation of the Access protocol in the Elixir 1.1.0 release.
